[versions]
appcompat = "1.7.0"
concurrentFutures = "1.1.0"
core = "1.48.0"
coreKtx = "1.16.0"
kotlin = "2.1.21"
material = "1.12.0"
obj = "0.4.0"
playServicesLocation = "19.0.1"
playServicesAuth = "19.0.0"
[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
core = { module = "com.google.ar:core", version.ref = "core" }
material = { module = "com.google.android.material:material", version.ref = "material" }
obj = { module = "de.javagl:obj", version.ref = "obj" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }# This file was generated by the Gradle 'init' task.
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
